version: "3.8"
services:
  warp-clash:
    build: .
    ports:
      - "21001:3000"
    env_file:
      - stack.env
    networks:
      drct:
        ipv4_address: 10.10.255.12
    volumes:
      - config:/app/config
      - account:/app/account
      - logs:/app/logs
networks:
  drct:
    name: drct_net
    external: true
volumes:
  config:
  account:
  logs:
