name: Docker Build and Push (linux/arm/v7)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: vvbbnn00/warp-clash-api
          tags: |
            type=sha,format=short

      - name: Build and push (Dockerfile.armhf)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.armhf
          push: true
          tags: ${{ steps.meta.outputs.tags }}-armv7
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: GITHUB_ACTIONS=true
          platforms: linux/arm/v7

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}
